apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - image: redis:alpine
        name: redis
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - mountPath: /data
          name: redis-data
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
            ephemeral-storage: "50Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
            ephemeral-storage: "100Mi"
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 10000 # BEGIN: Set runAsUser to a value > 10000
          runAsGroup: 10000 # BEGIN: Set runAsGroup to a value > 10000
        readinessProbe: # BEGIN: Added readiness probe
          tcpSocket:
            port: 6379
        imagePullPolicy: Always # BEGIN: Set ImagePullPolicy to Always
      volumes:
      - name: redis-data
        emptyDir: {}
