apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 10000
      containers:
      - image: dockersamples/examplevotingapp_vote:lastest
        name: vote
        ports:
        - containerPort: 80
          name: vote
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
            ephemeral-storage: "50Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
            ephemeral-storage: "100Mi"
        securityContext:
          readOnlyRootFilesystem: true
