apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001  # BEGIN: Set higher user ID
        runAsGroup: 10001  # Set higher group ID
      containers:
      - image: dockersamples/examplevotingapp_worker:lastest
        name: worker
        imagePullPolicy: Always  # Set ImagePullPolicy to Always
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
            ephemeral-storage: "50Mi"  # Set ephemeral storage limit
          limits:
            cpu: "200m"
            memory: "512Mi"
            ephemeral-storage: "100Mi"  # Set ephemeral storage limit
        securityContext:
          readOnlyRootFilesystem: true
