name: Continuous Integration for PR
on:
  pull_request:
    branches:
      - 'task-6-1'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'task-6-1/backend'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.18.0'
    - name: Install dependencies
      run: npm install
    - name: Run lint
      run: npm run lint
    - name: Check for non-doc changes
      id: doc-check
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -qvE '\.md$'; then
          echo "run_tests=true" >> $GITHUB_ENV
        else
          echo "run_tests=false" >> $GITHUB_ENV
        fi
    - name: Run tests
      if: env.run_tests == 'true'
      run: npm test
