name: K8s yaml validation - PUSH
on:
  push:
    branches:
      - task-6-3-dev

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: validate manifests k8s dir
        uses: makocchi-git/actions-k8s-manifests-validate-conftest@v1.2.0
        with:
          file: 'task-6-3/k8s'
          trace: true
          comment: false
