name: K8s - PR
on:
  pull_request:
    branches:
      - 'task-6-3'

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: validate manifests k8s dir
        uses: makocchi-git/actions-k8s-manifests-validate-conftest@v1.2.0
        with:
          file: .
          comment: 'task-6-3/k8s'
          token: ${{ secrets.TASK_6_3_PR_TOKEN }}

    