name: K8s - PR
on:
  pull_request:
    branches:
      - 'task-6-3'

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          setup-tools: |
            kubeconform
            kube-score
          kubeconform: '0.5.0'
          kube-score: '1.16.1'
      
      - name: Run kubelinter
        uses: stackrox/kube-linter-action@v1.0.2
        with:
          directory: task-6-3/k8s
          config: .kube-linter.yaml

      - name: Run kubeconform
        run: |
          kubeconform -kubernetes-version=1.24.0 task-6-3/k8s
          kubeconform -kubernetes-version=1.23.0 task-6-3/k8s
          kubeconform -kubernetes-version=1.22.0 task-6-3/k8s

      - name: Run kubescore scanner
        run: kube-score score task-6-3/k8s/*.yaml || true
