name: Release Workflow

on:
  push:
    tags:
      - '*'
    branches:
      - 'task-6-1'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: 'task-6-1/backend'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t my-image:${{ github.ref_name }} .
          docker tag my-image:${{ github.ref_name }} ${{ steps.login-ecr.outputs.registry }}/my-image:${{ github.ref_name }}

      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@0.2.1
        with:
          image-ref: 'my-image:${{ github.ref_name }}'
          format: 'table'
          exit-code: '1'  # Causes the workflow to fail if vulnerabilities are found
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/my-image:${{ github.ref_name }}

