name: Deploy Application

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag version to deploy'
        required: true

jobs:
  approval:
    runs-on: ubuntu-latest
    outputs:
      issue-url: ${{ steps.approval.outputs.issue-url }}  # Assuming the action outputs the URL of the created issue
    steps:
      - name: Manual approval
        id: approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.TOKEN }}  # Ensure you are using the correct token variable
          minimum-approvals: 1
          approvers: minchenlee

  notify:
    needs: approval
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          ISSUE_URL="${{ needs.approval.outputs.issue-url }}"
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"Deployment approval needed: [Approve Deployment]($ISSUE_URL)\"}" \
          $DISCORD_WEBHOOK_URL

  deploy:
    needs: notify
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: SSH into EC2 instance and deploy Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker pull ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{ github.event.inputs.version }}
            docker stop backend || true
            docker rm backend || true
            docker run --name backend -d ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{ github.event.inputs.version }}
