name: K8s - PR
on:
  pull_request:
    branches:
      - 'task-6-3'

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          setup-tools: |
            kubeconform
            kustomize
          kubeconform: '0.5.0'
          kustomize: '4.5.7'
      - run: |
          kubeconform task-6-3/k8s
          