name: Terraform Validation - PUSH

on:
  push:
    branches:
      - 'task-6-2-dev'
    paths:
      - 'task-6-2/terraform/**'

jobs:
  validate:
    defaults:
      run:
        working-directory: 'task-6-2/terraform'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.6.6'

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
