name: K8s - PR
on:
  pull_request:
    branches:
      - 'task-6-3'

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          setup-tools: |
            kubeconform
            kube-score
          kubeconform: '0.5.0'
          kube-score: '1.16.1'
      
      - name: Run kubelinter
        uses: stackrox/kube-linter-action@v1.0.2
        with:
          directory: task-6-3/k8s
          config: .kube-linter.yaml

      - name: Run kubeconform
        run: |
          kubeconform -kubernetes-version=1.24.0 task-6-3/k8s
          kubeconform -kubernetes-version=1.23.0 task-6-3/k8s
          kubeconform -kubernetes-version=1.22.0 task-6-3/k8s

      - name: Run kubescore scanner
        run: kube-score score task-6-3/k8s/*.yaml > kube-score-results.txt || true

      - name: Comment PR with the kube-score results
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.TASK_6_3_PR_TOKEN }}
          script: |
            const fs = require('fs');
            const results = fs.readFileSync('kube-score-results.txt', 'utf8');
            
            // Function to format the kube-score output
            function formatKubeScoreOutput(results) {
              return results.split('\n').map((line, index, lines) => {
                if (line.startsWith('apps/')) { // Assuming all relevant lines start with 'apps/'
                  // Insert a markdown header and an extra newline for spacing
                  return `\n### ${line}\n`;
                }
                // Add extra newlines between reports for better readability
                if (line.startsWith('[OK]') || line.startsWith('[CRITICAL]')) {
                  if (!(lines[index - 1] && lines[index - 1].startsWith('[OK]') || lines[index - 1].startsWith('[CRITICAL]'))) {
                    return `\n${line}`;
                  }
                }
                return line;
              }).join('\n');
            }

            let body = "## Kube-score results\n\n" + formatKubeScoreOutput(results);
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

