name: Destroy Terraform Resources
on:
  workflow_dispatch:
   action:
      description: 'Terraform Action to Perform'
      type: choice
      options:
      - Terraform_destroy

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  destroy:
    defaults:
      run:
        working-directory: 'task-6-2/terraform'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.6.6'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_GithubActionTerraformRole_ARN }}
      
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve -no-color
        continue-on-error: true

      - name: Fail if Destroy Fails
        if: failure()
        run: exit 1

