name: K8s - PR
on:
  pull_request:
    branches:
      - 'task-6-3'

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          setup-tools: |
            kubeconform
            kustomize
            kubeval
            kubesec
          kubeconform: '0.5.0'
          kubeval: '0.16.1'
          kubesec: '2.3.0'

      - uses: stackrox/kube-linter-action@v1.0.2
        with:
          directory: task-6-3/k8s

      - run: |
          kubeconform -kubernetes-version=1.24.0 task-6-3/k8s
          kubeconform -kubernetes-version=1.23.0 task-6-3/k8s
          kubeconform -kubernetes-version=1.22.0 task-6-3/k8s
      - run: |
          kubeval task-6-3/k8s
          kube-linter lint task-6-3/k8s --auto-fix
      - run: |
          kubesec scan task-6-3/k8s
